# .github/workflows/firebase-hosting-merge.yml

name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências (client)
        working-directory: ./client
        run: npm ci

      - name: Construir aplicação (client)
        working-directory: ./client
        run: npm run build

      - name: Deploy para Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTROLOBRA_3DCCE }}
          channelId: live
          projectId: controlobra-3dcce
          entryPoint: client
